### PR TITLE
Enforce JavaScript code formatting style

### PR DESCRIPTION
**Pull request by ottumm**
Resolves issue #12 

- introduces [jscs](http://jscs.info) into the build process
- lots of whitespace changes

### CODE REVIEW

**Comment by ottumm** [comment]
(I will definitely squash commits once this has been reviewed)

**Comment by ottumm** [comment]
Pull request #13 needs to be merged before this one. Once that's done I'll fix up the commit history.

**Comment by ottumm** [comment]
@amcgee this is ready for review.

**Comment by amcgee** [comment]
Such style!  Looks good.

**Pull request merged**
